version: "3.8"
services:
  frontend:
    image: 
    volumes:
      - 
    restart: 
    environment:
      - name=value
    networks:
      - matgo
    ports:
      - 30080:80
  backend:
    image: 
    volumes:
      - 
    restart: 
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
        MONGO_DB_PW=${MONGO_DB_PW}
        MONGO_DB_IP=${MONGO_DB_IP}
        MONGO_DB_NAME=${MONGO_DB_NAME}
        MONGO_DB_PORT=${MONGO_DB_PORT}
    networks:
      - matgo
    ports:
      - 38080:8080
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - 
    restart: 
    environment:
      - name=value
    networks:
      - matgo
    ports:
      - 37017:27017
  gitlab:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - 
    restart: 
    environment:
      - name=value
    networks:
      - matgo
    ports:
      - 31080:80
        31443:443
        31022:22

volumes:

networks:
  matgo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
          ip_range: 172.30.1.0/26
          gateway: 172.30.1.1