version: "3.8"
services:
  # frontend:
  #   image: # 이미지 정의 필요
  #   volumes:
  #     - ./frontend/app/logs:/app/logs
  #   restart: unless-stopped
  #   environment:
  #     - name=value
  #   networks:
  #     - matgo
  #   ports:
  #     - 30080:80
  # backend:
  #   image: # 이미지 정의 필요
  #   volumes:
  #     - ./backend/app/logs:/app/logs
  #   restart: unless-stopped
  #   environment:
  #     - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
  #       MONGO_DB_PW=${MONGO_DB_PW}
  #       MONGO_DB_IP=${MONGO_DB_IP}
  #       MONGO_DB_NAME=${MONGO_DB_NAME}
  #       MONGO_DB_PORT=${MONGO_DB_PORT}
  #   networks:
  #     - matgo
  #   ports:
  #     - 38080:8080
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - ./mongodb/data:/data/db
    restart: unless-stopped 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - matgo
    ports:
      - 37017:27017
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - ./gitlab/log:/var/log/gitlab
        ./gitlab/opt:/var/opt/gitlab
    restart: unless-stopped
    environment:
      - name=value
    networks:
      - matgo
    ports:
      - 31080:80
        31443:443
        31022:22
networks:
  matgo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
          ip_range: 172.30.1.0/26
          gateway: 172.30.1.1