services:
  # frontend:
  #   image: matgo-frontend:0.0.1
  #   volumes:
  #     - ./frontend/app/logs:/app/logs
  #   restart: unless-stopped
  #   environment:
  #     - name=value
  #   networks:
  #     - matgo
  #   ports:
  #     - "30080:80"
  # backend:
  #   image: matgo-backend:0.0.1
  #   volumes:
  #     - ./backend/app/logs:/app/logs
  #   restart: unless-stopped
  #   environment:
  #     - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
  #       MONGO_DB_PW=${MONGO_DB_PW}
  #       MONGO_DB_IP=${MONGO_DB_IP}
  #       MONGO_DB_NAME=${MONGO_DB_NAME}
  #       MONGO_DB_PORT=${MONGO_DB_PORT}
  #   networks:
  #     - matgo
  #   ports:
  #     - "38080:8080"
  mongodb:
    image: mongo:7.0.15
    volumes:
      - ./mongodb/data:/data
    restart: unless-stopped
    env_file:
      - ./mongodb.env
    networks:
      - matgo
    ports:
      - "37017:27017"
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - ./gitlab/log:/var/log/gitlab
        ./gitlab/opt:/var/opt/gitlab
    restart: unless-stopped
    environment:
      - name=value
    networks:
      - matgo
    ports:
      - "31080:80"
      - "31443:443"
      - "31022:22"
networks:
  matgo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
          ip_range: 172.30.1.0/26
          gateway: 172.30.1.1