global:
  ingress:
    configureCertmanager: false  
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    enabled: true
    class: nginx  
    tls:
      enabled: true
      secretName: gitlab-tls 

nginx-ingress:
  enabled: false

certmanager:
  install: false