existingconfigMap: ""
configInline:
  address-pools:
  - name: ip-pool
    protocol: layer2
    addresses:
    - 192.168.0.111-192.168.0.120
serviceAccounts:
  controller:
    create: true
    name: "controller"
  speaker:
    create: true
    name: "speaker"